In [17]:
import numpy as np
import pandas as pd

In [18]:
x = [1,2,3,5,7,8,4,9]
nx = np.array(x)

In [19]:
print(nx)

[1 2 3 5 7 8 4 9]


In [20]:
print(nx.shape)

(8,)


In [21]:
ny = np.array([[1,2,3],[5,6,7]])

In [22]:
print(ny.shape)

(2, 3)


In [23]:
ny

array([[1, 2, 3],
       [5, 6, 7]])

In [24]:
one = np.arange(1,100,.2)
one

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,
        5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,
        7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,
        9.8, 10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8,
       12. , 12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. ,
       14.2, 14.4, 14.6, 14.8, 15. , 15.2, 15.4, 15.6, 15.8, 16. , 16.2,
       16.4, 16.6, 16.8, 17. , 17.2, 17.4, 17.6, 17.8, 18. , 18.2, 18.4,
       18.6, 18.8, 19. , 19.2, 19.4, 19.6, 19.8, 20. , 20.2, 20.4, 20.6,
       20.8, 21. , 21.2, 21.4, 21.6, 21.8, 22. , 22.2, 22.4, 22.6, 22.8,
       23. , 23.2, 23.4, 23.6, 23.8, 24. , 24.2, 24.4, 24.6, 24.8, 25. ,
       25.2, 25.4, 25.6, 25.8, 26. , 26.2, 26.4, 26.6, 26.8, 27. , 27.2,
       27.4, 27.6, 27.8, 28. , 28.2, 28.4, 28.6, 28.8, 29. , 29.2, 29.4,
       29.6, 29.8, 30. , 30.2, 30.4, 30.6, 30.8, 31

In [25]:
print(one.size)

495


In [26]:
two = np.linspace(0,100,200)
two

array([  0.        ,   0.50251256,   1.00502513,   1.50753769,
         2.01005025,   2.51256281,   3.01507538,   3.51758794,
         4.0201005 ,   4.52261307,   5.02512563,   5.52763819,
         6.03015075,   6.53266332,   7.03517588,   7.53768844,
         8.04020101,   8.54271357,   9.04522613,   9.54773869,
        10.05025126,  10.55276382,  11.05527638,  11.55778894,
        12.06030151,  12.56281407,  13.06532663,  13.5678392 ,
        14.07035176,  14.57286432,  15.07537688,  15.57788945,
        16.08040201,  16.58291457,  17.08542714,  17.5879397 ,
        18.09045226,  18.59296482,  19.09547739,  19.59798995,
        20.10050251,  20.60301508,  21.10552764,  21.6080402 ,
        22.11055276,  22.61306533,  23.11557789,  23.61809045,
        24.12060302,  24.62311558,  25.12562814,  25.6281407 ,
        26.13065327,  26.63316583,  27.13567839,  27.63819095,
        28.14070352,  28.64321608,  29.14572864,  29.64824121,
        30.15075377,  30.65326633,  31.15577889,  31.65

In [27]:
print(two.size)

200


In [28]:
three = np.random.rand(100)

In [29]:
three

array([0.33041086, 0.1831397 , 0.65699745, 0.53280537, 0.18815893,
       0.40080019, 0.20530709, 0.79482816, 0.30273299, 0.41961322,
       0.52943508, 0.50145504, 0.09584492, 0.15548795, 0.40037882,
       0.20835624, 0.10515421, 0.18929577, 0.5094681 , 0.94320399,
       0.26562812, 0.34547335, 0.15162593, 0.90895278, 0.23168628,
       0.57422908, 0.2370368 , 0.79579942, 0.45675934, 0.10136417,
       0.01241065, 0.8861784 , 0.56199112, 0.4369273 , 0.1143463 ,
       0.17576068, 0.57190138, 0.3583102 , 0.09398744, 0.41723877,
       0.59339297, 0.98541694, 0.96763946, 0.68960841, 0.34641929,
       0.87563927, 0.74611023, 0.84030263, 0.24874964, 0.05824197,
       0.98511021, 0.40505402, 0.74613012, 0.87804942, 0.91502578,
       0.7479648 , 0.97285704, 0.52190589, 0.88197994, 0.63484248,
       0.70752692, 0.32269703, 0.14995636, 0.00785136, 0.59381817,
       0.01276741, 0.46511245, 0.22607096, 0.63754067, 0.24057181,
       0.68124317, 0.30659279, 0.39028028, 0.89634599, 0.25883

In [30]:
four = np.random.randint(1,10,100)
four

array([4, 7, 6, 6, 7, 5, 3, 8, 5, 9, 7, 4, 3, 4, 5, 8, 3, 2, 1, 6, 2, 3,
       5, 8, 4, 8, 8, 4, 2, 5, 8, 2, 8, 3, 4, 1, 3, 8, 7, 3, 7, 2, 4, 2,
       8, 6, 9, 2, 5, 7, 1, 3, 7, 3, 5, 1, 1, 4, 3, 4, 5, 1, 4, 6, 9, 5,
       2, 2, 8, 3, 5, 9, 2, 2, 4, 1, 8, 8, 1, 6, 5, 7, 2, 2, 2, 8, 1, 2,
       5, 9, 9, 4, 6, 7, 1, 2, 6, 8, 6, 6])

In [31]:
four.reshape((10,10))

array([[4, 7, 6, 6, 7, 5, 3, 8, 5, 9],
       [7, 4, 3, 4, 5, 8, 3, 2, 1, 6],
       [2, 3, 5, 8, 4, 8, 8, 4, 2, 5],
       [8, 2, 8, 3, 4, 1, 3, 8, 7, 3],
       [7, 2, 4, 2, 8, 6, 9, 2, 5, 7],
       [1, 3, 7, 3, 5, 1, 1, 4, 3, 4],
       [5, 1, 4, 6, 9, 5, 2, 2, 8, 3],
       [5, 9, 2, 2, 4, 1, 8, 8, 1, 6],
       [5, 7, 2, 2, 2, 8, 1, 2, 5, 9],
       [9, 4, 6, 7, 1, 2, 6, 8, 6, 6]])

In [32]:
four.reshape((10,5,2))

array([[[4, 7],
        [6, 6],
        [7, 5],
        [3, 8],
        [5, 9]],

       [[7, 4],
        [3, 4],
        [5, 8],
        [3, 2],
        [1, 6]],

       [[2, 3],
        [5, 8],
        [4, 8],
        [8, 4],
        [2, 5]],

       [[8, 2],
        [8, 3],
        [4, 1],
        [3, 8],
        [7, 3]],

       [[7, 2],
        [4, 2],
        [8, 6],
        [9, 2],
        [5, 7]],

       [[1, 3],
        [7, 3],
        [5, 1],
        [1, 4],
        [3, 4]],

       [[5, 1],
        [4, 6],
        [9, 5],
        [2, 2],
        [8, 3]],

       [[5, 9],
        [2, 2],
        [4, 1],
        [8, 8],
        [1, 6]],

       [[5, 7],
        [2, 2],
        [2, 8],
        [1, 2],
        [5, 9]],

       [[9, 4],
        [6, 7],
        [1, 2],
        [6, 8],
        [6, 6]]])

In [33]:
one = np.random.randint(1,10,(5,5))
two = np.random.randint(1,10,(5,5))

In [34]:
one + two

array([[ 5,  3, 13, 16, 12],
       [ 8, 11, 10, 11, 15],
       [13, 11, 11, 14, 10],
       [ 4, 10, 14,  6,  9],
       [ 4, 12, 14,  8,  9]])

In [35]:
one - two

array([[ 1,  1,  3,  0, -2],
       [ 4,  7,  0,  7,  1],
       [ 5, -3, -3, -4,  8],
       [ 0,  4,  2,  4, -1],
       [ 2, -6,  2, -4,  7]])

In [36]:
one ** 4

array([[  81,   16, 4096, 4096,  625],
       [1296, 6561,  625, 6561, 4096],
       [6561,  256,  256,  625, 6561],
       [  16, 2401, 4096,  625,  256],
       [  81,   81, 4096,   16, 4096]], dtype=int32)

In [37]:
one + 10

array([[13, 12, 18, 18, 15],
       [16, 19, 15, 19, 18],
       [19, 14, 14, 15, 19],
       [12, 17, 18, 15, 14],
       [13, 13, 18, 12, 18]])

In [38]:
one.dot(two)

array([[ 63, 132, 159, 138,  88],
       [ 76, 158, 212, 168, 163],
       [ 61, 141, 177, 175, 129],
       [ 64, 123, 155, 131, 100],
       [ 56, 143, 146, 152,  68]])

In [39]:
one * two

array([[ 6,  2, 40, 64, 35],
       [12, 18, 25, 18, 56],
       [36, 28, 28, 45,  9],
       [ 4, 21, 48,  5, 20],
       [ 3, 27, 48, 12,  8]])

In [40]:
one / two

array([[1.5       , 2.        , 1.6       , 1.        , 0.71428571],
       [3.        , 4.5       , 1.        , 4.5       , 1.14285714],
       [2.25      , 0.57142857, 0.57142857, 0.55555556, 9.        ],
       [1.        , 2.33333333, 1.33333333, 5.        , 0.8       ],
       [3.        , 0.33333333, 1.33333333, 0.33333333, 8.        ]])

In [41]:
n6 = np.random.randint(1,10,10)

In [42]:
n6

array([2, 8, 9, 4, 8, 3, 5, 9, 8, 5])

In [43]:
n6[0]

2

In [44]:
n6[-1]

5

In [45]:
n6[:5]

array([2, 8, 9, 4, 8])

In [46]:
n6[5:]

array([3, 5, 9, 8, 5])

In [47]:
n7 = np.array([[1,2,3,4],[5,6,7,8],[9,7,8,6]])

In [48]:
n7

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 7, 8, 6]])

In [49]:
print(n7[0])

[1 2 3 4]


In [50]:
print(n7[: ,0])

[1 5 9]


In [51]:
print(n7[-1])

[9 7 8 6]


In [52]:
print(n7[:2, 2:])

[[3 4]
 [7 8]]


In [53]:
print(n7[1:, 0:])

[[5 6 7 8]
 [9 7 8 6]]


In [54]:
four.flatten()

array([4, 7, 6, 6, 7, 5, 3, 8, 5, 9, 7, 4, 3, 4, 5, 8, 3, 2, 1, 6, 2, 3,
       5, 8, 4, 8, 8, 4, 2, 5, 8, 2, 8, 3, 4, 1, 3, 8, 7, 3, 7, 2, 4, 2,
       8, 6, 9, 2, 5, 7, 1, 3, 7, 3, 5, 1, 1, 4, 3, 4, 5, 1, 4, 6, 9, 5,
       2, 2, 8, 3, 5, 9, 2, 2, 4, 1, 8, 8, 1, 6, 5, 7, 2, 2, 2, 8, 1, 2,
       5, 9, 9, 4, 6, 7, 1, 2, 6, 8, 6, 6])

In [55]:
# flatten a n dimension matrix  to 1 diemefornsion matrix
four.ravel()

array([4, 7, 6, 6, 7, 5, 3, 8, 5, 9, 7, 4, 3, 4, 5, 8, 3, 2, 1, 6, 2, 3,
       5, 8, 4, 8, 8, 4, 2, 5, 8, 2, 8, 3, 4, 1, 3, 8, 7, 3, 7, 2, 4, 2,
       8, 6, 9, 2, 5, 7, 1, 3, 7, 3, 5, 1, 1, 4, 3, 4, 5, 1, 4, 6, 9, 5,
       2, 2, 8, 3, 5, 9, 2, 2, 4, 1, 8, 8, 1, 6, 5, 7, 2, 2, 2, 8, 1, 2,
       5, 9, 9, 4, 6, 7, 1, 2, 6, 8, 6, 6])

In [56]:
four.T

array([4, 7, 6, 6, 7, 5, 3, 8, 5, 9, 7, 4, 3, 4, 5, 8, 3, 2, 1, 6, 2, 3,
       5, 8, 4, 8, 8, 4, 2, 5, 8, 2, 8, 3, 4, 1, 3, 8, 7, 3, 7, 2, 4, 2,
       8, 6, 9, 2, 5, 7, 1, 3, 7, 3, 5, 1, 1, 4, 3, 4, 5, 1, 4, 6, 9, 5,
       2, 2, 8, 3, 5, 9, 2, 2, 4, 1, 8, 8, 1, 6, 5, 7, 2, 2, 2, 8, 1, 2,
       5, 9, 9, 4, 6, 7, 1, 2, 6, 8, 6, 6])

In [57]:
four.max()

9

In [58]:
four.min()

1

In [59]:
four.mean()

4.72

In [60]:
four.sum()

472

In [61]:
four.sum(axis=0) # sum all values in each coloumn

472

In [62]:
four.std()

2.4903011866037414

In [63]:
n7.max() # the value

9

In [ ]:
print(n7, n7.max(),"found")

In [64]:
n7.argmax() # the index of the max value

8

In [65]:
a = np.random.randint(1,100, (3,2))
b = np.random.randint(1,100, (3,2))
c = np.random.randint(1,100, (2,3))
print(a)
print(b)
print(c)

[[20 29]
 [43 29]
 [83 75]]
[[84 33]
 [ 6 16]
 [60  7]]
[[50  4  5]
 [19 24 37]]


In [66]:
np.hstack((a,b)) # horizontal stack

array([[20, 29, 84, 33],
       [43, 29,  6, 16],
       [83, 75, 60,  7]])

In [67]:
np.vstack((a,b)) # vertical stack

array([[20, 29],
       [43, 29],
       [83, 75],
       [84, 33],
       [ 6, 16],
       [60,  7]])

In [68]:
np.vstack((a,c.T))

array([[20, 29],
       [43, 29],
       [83, 75],
       [50, 19],
       [ 4, 24],
       [ 5, 37]])

In [70]:
m = np.array([1,2,3,4,5,6,7,8,9,2,4,5,1,7,9,6,5,7,3,5,4,8,8,5,9,6])

In [71]:
# boolen filter
m > 5

array([False, False, False, False, False,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True, False,  True,
       False, False, False,  True,  True, False,  True,  True])

In [72]:
m[m > 5]

array([6, 7, 8, 9, 7, 9, 6, 7, 8, 8, 9, 6])

In [73]:
m[m == 5]

array([5, 5, 5, 5, 5])

In [74]:
m[m != 5]

array([1, 2, 3, 4, 6, 7, 8, 9, 2, 4, 1, 7, 9, 6, 7, 3, 4, 8, 8, 9, 6])

In [75]:
# in range of 2 to 8 
m[((m>2) & (m<8))]

array([3, 4, 5, 6, 7, 4, 5, 7, 6, 5, 7, 3, 5, 4, 5, 6])

In [76]:
# user created numpy matrix
mat = []
for i in range(10):
    mat.append(int(input('Enter value')))
mat = np.array(mat)

In [77]:
print(mat, mat.shape)

[2 4 6 4 7 8 9 3 1 5] (10,)


In [79]:
# user created numpy matrix
mat = []
for i in range(2):
    smat = []
    for j in range(3):
        smat.append(int(input('Enter value')))
    mat.append(smat)
mat = np.array(mat)
print(mat, mat.shape)

[[2 4 5]
 [6 7 8]] (2, 3)
